server:
  port: 8086
logging:                                # 配置日志级别
  level:
    root: INFO
    com.kingmed.dp: INFO
    org.hibernate.SQL: debug
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
feign:  
  hystrix:
    enabled: true    