server:
  port: 8081
spring:
  application:
    name: dp-event-source
  data:
    mongodb.uri: mongodb://192.168.0.124:27017/dp-event-source
    
logging:                                # 配置日志级别
  level:
    root: INFO
    com.kingmed.dp: INFO
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true